export const siteUrl = "https://penguin.photos";
export const siteTitle = "Penguin Photos";
export const siteDescription = "ペンギンの画像集";
export const siteAuthor = "meil";
export const siteStartYear = 2018;
export const twitter = "penguin_sharp";
export const github = "MeilCli";
export const pagingCount = 8;
export const analyticsId = "G-82V50XPY55";
